In [431]:
import numpy as np
from numpy import array 
eps = np.finfo(np.float64).eps

In [425]:
inputs = array([[[[ 181., 180., 599., 427., -347., -835.], 
                [ 329., -493., 1006., -575.,  147., -685.],
                [-571., -384., -539.,  818.,  955.,  564.],
                [-629., -546., -325.,  282.,  330., -641.],
                [ 388., -924., -191., 1021., -930.,  478.],
                [-281., -292., -939.,  738.,  356., -164.]]]])

In [426]:
inputs.shape

(1, 1, 6, 6)

In [573]:
gamma=array([1008.])
beta=array([641.])
running_mean=array([269.93])
running_var=array([1133.14])
inputs=array([[[[-315.]]], [[[ 247.]]]])
grad_outputs=array([[[[122.]]], [[[256.]]]])

forward_normalized_inputs = array([[[[-1.]]], [[[ 1.]]]])
# forward_normalized_inputs = inputs
forward_inverse_std = array([0.00355872])

In [574]:
n, d, h, w = grad_outputs.shape
        
dl_dn = grad_outputs * gamma[:, None, None, None]
grad = w * h * dl_dn - np.sum(dl_dn, axis = (-2, -1), keepdims = True) - forward_normalized_inputs * np.sum(dl_dn * forward_normalized_inputs, axis = (-2, -1), keepdims = True)
grad = grad * forward_inverse_std[:, None, None, None] / w / h

In [575]:
grad

array([[[[-437.63715072]]],


       [[[-918.32057856]]]])

In [508]:
grad.shape

(2, 1, 2, 1)

In [613]:
np.sum(dl_dn, axis = 0, keepdims = True)

array([[[[381024.]]]])

In [624]:
grad = n * dl_dn - np.sum(dl_dn, axis = 0, keepdims = True) - forward_normalized_inputs * np.sum(dl_dn * forward_normalized_inputs, axis = 0, keepdims = True)

In [625]:
grad

array([[[[0.]]],


       [[[0.]]]])

In [616]:
grad = w * h * dl_dn

In [617]:
grad

array([[[[122976.]]],


       [[[258048.]]]])

In [618]:
grad = np.sum(dl_dn, axis = (-2, -1))[:, None, None]

In [619]:
grad

array([[[[122976.]]],


       [[[258048.]]]])

In [620]:
grad = forward_normalized_inputs * np.sum(dl_dn * forward_normalized_inputs, axis = (-2, -1))[:, None, None]

In [621]:
grad

array([[[[122976.]]],


       [[[258048.]]]])